apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: example
  namespace: jenkins
spec:
  configurationAsCode:
    configurations: []
    secret:
      name: ""
  groovyScripts:
    configurations: []
    secret:
      name: ""
  jenkinsAPISettings:
    authorizationStrategy: createUser
  master:
    disableCSRFProtection: false
    basePlugins:
      - name: kubernetes
        version: "1.31.1"
      - name: kubernetes-credentials
        version: "0.9.0"
      - name: kubernetes-credentials-provider
        version: "0.20"
      - name: configuration-as-code
        version: "1.55"
      - name: job-dsl
        version: "1.78.1"
      - name: git
        version: "4.10.1"
      - name: workflow-aggregator
        version: "2.6"
      - name: workflow-job
        #        version: "2.42"
        version: "1145.v7f2433caa07f"
    plugins:
      - name: pipeline-graph-analysis
        #        version: "1.12"
        version: "188.v3a01e7973f2c"
      - name: git
        version: "4.10.1"
      - name: jaxb
        version: "2.3.0.1"
      - name: command-launcher
        version: "1.6"
      - name: jdk-tool
        version: "1.5"
      - name: kubernetes-client-api
        version: "5.10.1-171.vaa0774fb8c20"
    containers:
      - name: jenkins-master
        image: jenkins/jenkins:2.326-alpine
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 12
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 10
          httpGet:
            path: /login
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 3Gi
          requests:
            cpu: "1"
            memory: 500Mi
